spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jpatest
    username: root
    password: Venusinfurs92
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
      format_sql: true
